=== Alex-notfound/Pedidos-APP-Local/pedidos-app-local/pedidos.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.pedidos-app-local.es/app" xmlns:tns="http://www.pedidos-app-local.es/app">

    <element name="root">
        <complexType>
            <sequence>
                <element name="pedido" type="tns:pedido" minOccurs="1" maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <complexType name="pedido">
        <sequence>
            <element name="referencia" type="string" minOccurs="1" maxOccurs="1" />
            <element name="fechaPedido" type="date" minOccurs="1" maxOccurs="1" />
            <element name="fechaEntrega" type="date" minOccurs="0" maxOccurs="1" />
            <element name="precio" type="decimal" default="0.0" minOccurs="1" maxOccurs="1" />
            <element name="urgente" type="boolean" minOccurs="1" maxOccurs="1" />
            <element name="mueble" type="tns:mueble" minOccurs="1" maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="mueble">
        <sequence>
            <element name="id" type="integer" minOccurs="1" maxOccurs="1" />
            <element name="unidades" type="integer" minOccurs="1" maxOccurs="1" />
            <element name="tipo" type="string" minOccurs="1" maxOccurs="1" />
            <element name="modelo" type="string" minOccurs="1" maxOccurs="1" />
            <element name="color" type="string" minOccurs="1" maxOccurs="1" />
            <element name="grosor" type="integer" minOccurs="1" maxOccurs="1" />
            <element name="medidas" type="string" minOccurs="1" maxOccurs="1" />
            <element name="descripcion" type="string" minOccurs="0" maxOccurs="1" />
            <element name="precioUnidad" type="decimal" default="0.0" minOccurs="1" maxOccurs="1" />
        </sequence>
    </complexType>
</schema>

=== Alex-notfound/Pedidos-APP-Local/pedidos-app-local/pedidos.xml
<?xml version="1.0" encoding="UTF-8"?>

<tns:root xmlns:tns="http://www.pedidos-app-local.es/app" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pedidos-app-local.es/app pedidos.xsd ">

    <pedido>
        <referencia>ZA-101312</referencia>
        <fechaPedido>2021-03-08</fechaPedido>
        <fechaEntrega>2022-03-08</fechaEntrega>
        <precio>150.51</precio>
        <urgente>true</urgente>
        <mueble>
            <id>1</id>
            <unidades>1</unidades>
            <tipo>Mesilla</tipo>
            <modelo>Laurica</modelo>
            <color>N贸rdico</color>
            <grosor>4</grosor>
            <medidas>80x70x50</medidas>
            <descripcion>Esto es una descripci贸n</descripcion>
            <precioUnidad>23.47</precioUnidad>
        </mueble>
        <mueble>
            <id>2</id>
            <unidades>2</unidades>
            <tipo>Sinfonier</tipo>
            <modelo>Martica</modelo>
            <color>Nogal</color>
            <grosor>3</grosor>
            <medidas>140x30x60</medidas>
            <precioUnidad>70.00</precioUnidad>
        </mueble>
    </pedido>

    <pedido>
        <referencia>BA-151219</referencia>
        <fechaPedido>2021-03-09</fechaPedido>
        <fechaEntrega>2022-03-10</fechaEntrega>
        <precio>200</precio>
        <urgente>false</urgente>
        <mueble>
            <id>1</id>
            <unidades>1</unidades>
            <tipo>Mesilla</tipo>
            <modelo>Laurica</modelo>
            <color>N贸rdico</color>
            <grosor>4</grosor>
            <medidas>80x70x50</medidas>
            <descripcion>Esto es una descripci贸n</descripcion>
            <precioUnidad>23.47</precioUnidad>
        </mueble>
        <mueble>
            <id>2</id>
            <unidades>2</unidades>
            <tipo>Sinfonier</tipo>
            <modelo>Martica</modelo>
            <color>Nogal</color>
            <grosor>3</grosor>
            <medidas>140x30x60</medidas>
            <precioUnidad>70.00</precioUnidad>
        </mueble>
    </pedido>

</tns:root>
